AUTH/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import login_or_register, info, anonimus, logout_view


app_name = 'auth'
urlpatterns = [
    path('', info, name='info'),
    path('auth/', login_or_register.as_view(), name='auth'),
    path('hello/', anonimus, name='anonimus'),
    path('logout/', logout_view, name='logout'),
]

card_surveys/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect


app_name = 'base'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('AUTH.urls'), name='account'),
    path('surveys/', include('surveys.urls'), name='surveys'),
    path('', lambda request: redirect('surveys:list')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

surveys/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import List, survey_info, survey_process, survey_result, new_survey, your_surveys


app_name = 'surveys'
urlpatterns = [
    path('', List, name='list'),
    path('new/', new_survey.as_view(), name='new'),
    path('your_surveys/', your_surveys, name='your_surveys'),
    path('<int:survey_id>/', survey_info, name='info'),
    path('<int:survey_id>/process', survey_process, name='process'),
    path('<int:survey_id>/result', survey_result, name='result'),
]

surveys/models.py
from django.db import models
from django.db.models import JSONField
from AUTH.models import User

class Survey(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=255)
    description = models.TextField()
    avatar = models.ImageField(upload_to='survey_avatars/', default='survey_avatars/default_survey.jpg')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='created_surveys')
    participants = models.ManyToManyField(User, related_name='surveys_participant', blank=True)
    last_updated = models.DateTimeField(auto_now=True)
    rate = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        if self.id:
            old_avatar = Survey.objects.get(pk=self.id).avatar
            if self.avatar and old_avatar != self.avatar:
                old_avatar.delete()
        super(Survey, self).save(*args, **kwargs)

class Card(models.Model):
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    body = models.TextField()
    avatar = models.ImageField(upload_to='card_avatars/', default='card_avatars/default_card.jpg')
    user_rates = JSONField(default=dict)
    last_updated = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if self.id:
            old_avatar = Card.objects.get(pk=self.id).avatar
            if self.avatar and old_avatar != self.avatar:
                old_avatar.delete()
        super(Card, self).save(*args, **kwargs)

surveys/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse

from django.views import View
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from .models import Survey

import string


def List(request):
    return render(request, 'list.html', {'user': request.user, 'surveys': Survey.objects.all().order_by('-rate')[:10]})

def survey_info(request, survey_id: int):
    return render(request, 'survey_info.html', {'survey': get_object_or_404(Survey, id=survey_id), 'user': request.user})

@login_required(login_url='auth:anonimus')
def survey_process(request, survey_id: int):
    return render(request, 'survey_process.html', {'survey': get_object_or_404(Survey, id=survey_id), 'user': request.user})

@login_required(login_url='auth:anonimus')
def survey_result(request, survey_id: int):
    return render(request, 'survey_result.html', {'survey': get_object_or_404(Survey, id=survey_id), 'user': request.user})

@login_required(login_url='auth:anonimus')
def your_surveys(request):
    return render(request, 'your_surveys.html', {'surveys': request.user.created_surveys.all(), 'user': request.user})

class new_survey(View):
    template_name = 'new_survey.html'

    @method_decorator(login_required(login_url='auth:anonimus'))
    def get(self, request):
        return render(request, self.template_name, {'user': request.user})

    def post(self, request):
        name = request.POST.get('name')
        description = request.POST.get('description')
        avatar = request.POST.get('avatar')

        if FormUtils.is_survey_name(name):
            Survey.objects.create(name=name, description=description, avatar=avatar, author=request.user)
            return redirect('surveys:your_surveys')
        else:
            return render(request, self.template_name, {'reg_error': f'Неправильое имя опроса {name}. При составлении имени можно использовать a-z, A-Z, 0-9, _, -, при этом он должен быть от 1 до 45 символов.'})


class FormUtils:
    def is_survey_name(name: str) -> bool:
        enabled_chars = string.ascii_letters + string.digits + '_-'
        max_length = 45
        min_length = 1

        if len(name) > max_length or len(name) < min_length:
            return False

        for char in name:
            if not char in enabled_chars:
                return False

        return True
        

surveys/templates/list.html
{% extends 'base.html' %}

{% block title %}Список опросов{% endblock %}

{% block content %}

<a href="{% url 'surveys:new' %}">Создать опрос</a>

<nav>
    <ul>
        {% for survey in surveys %}
            <li>
                <a href="{% url 'surveys:info' survey_id=survey.id %}">{{ survey.name }}</a>
                <img src="{{ survey.avatar.url }}" alt="Аватар опроса" class="user-avatar">
                <p>{{ survey.description|truncatechars:45 }}...</p>
                <p>Рейтинг: {{ survey.rate }}</p>
            </li>
        {% endfor %}
    </ul>
</nav>

{% endblock %}

surveys/templates/new_survey.html
{% extends 'base.html' %}

{% block title %}Создать опрос{% endblock %}

{% block content %}

<h2>Новый опрос</h2>
<form method="post" action="{% url 'surveys:new' %}">
    {% csrf_token %}
    <label for="name">Имя опроса:</label>
    <input type="text" name="name" required>
    <br>
    <label for="description">Описание опроса:</label>
    <textarea name="description" rows="4"></textarea>
    <br>
    <label for="avatar">Аватар опроса:</label>
    <input type="file" name="avatar" accept="image/*">
    <br>
    <button type="submit">Создать</button>
</form>
{{ error }}

{% endblock %}

surveys/templates/survey_info.html
{% extends 'base.html' %}

{% block title %}Об опросе{% endblock %}

{% block content %}
    4
{% endblock %}

surveys/templates/survey_process.html
{% extends 'base.html' %}

{% block title %}Процесс опроса{% endblock %}

{% block content %}
    2
{% endblock %}

surveys/templates/survey_result.html
{% extends 'base.html' %}

{% block title %}Результат опроса{% endblock %}

{% block content %}
    3
{% endblock %}

surveys/templates/your_surveys.html
{% extends 'base.html' %}

{% block title %}Список опросов{% endblock %}

{% block content %}

<a href="{% url 'surveys:new' %}">Создать опрос</a>

<nav>
    <ul>
        {% for survey in surveys %}
            <li><a href="{% url 'auth:info' %}">{{ survey.name }}</a>
                <img src="{{ user.avatar.url }}" alt="Твой аватар" class="user-avatar"></li>
        {% endfor %}
    </ul>
</nav>

{% endblock %}

templates/base.html
<!-- base.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Site{% endblock %}</title>
    <style>
        .user-avatar {
            width: 25px;
            height: 25px;
            border-radius: 20%;
        }
        .big-user-avatar {
            width: 200px;
            height: 200px;
            border-radius: 10%;
        }
    </style>
</head>
<body>

    <header>
        <nav>
            <ul>
                <li><a href="{% url 'surveys:list' %}">Опросы</a></li>
                {% if user.username != '' %}
                    <li><a href="{% url 'auth:info' %}">{{ user.username }}</a>
                        <img src="{{ user.avatar.url }}" alt="Твой аватар" class="user-avatar"></li>
                    <li><a href="{% url 'auth:logout' %}">Выход</a></li>
                {% else %}
                    <li><a href="{% url 'auth:auth' %}">Регистрация/Вход</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>

    <main>
        {% block content %}{% endblock %}
    </main>

</body>
</html>